version: '3.1'
services: # 컨테이너
    db:
        image: mysql:8.0.33
        container_name: mysql-hkidb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: hkidb
            TZ: Asia/Seoul
        ports:
            - "3306:3306"
        command:
            - --skip-character-set-client-handshake
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d

    redis_container:
        image: redis:6.2.5
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    core:
        image: mztrade/core:arm64
        container_name: mztrade-core
        restart: always
        ports:
            - "8080:8080"