version: '3.1'
services: # 컨테이너
    db:
        image: mysql:8.0.33
        container_name: mysql-hkidb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}
            MYSQL_DATABASE: hkidb
            TZ: Asia/Seoul
        ports:
            - ${RDS_PORT}:${RDS_PORT}
        command:
            - --skip-character-set-client-handshake
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d

    redis_container:
        image: redis:6.2.5
        container_name: redis
        restart: always
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}

    core:
        image: mztrade/core:arm64
        container_name: mztrade-core
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
