spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${RDS_USERNAME}
        url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/hkidb
        password: ${RDS_PASSWORD}
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

server.port: ${SERVER_PORT}

logging:
    level:
        com.mztrade: info
