spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hkidb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
        username: root
        password: 1234
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa: # 쿼리 수행시 콘솔창에 출력되는 옵션 추가
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    jwt:
        secret: aGtpZGItYmFja3Rlc3QtcHJvamVjdC1tenRyYWRlLWNvcmU= #base64로 인코딩한 secret 값