spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${RDS_HOST_NAME}:${RDS_PORT}/hkidb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
        username: ${RDS_USERNAME}
        password: ${RDS_PASSWORD}
    jackson:
        property-naming-strategy: SNAKE_CASE
# 쿼리 수행시 콘솔창에 출력되는 옵션 추가
#    jpa:
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true

    output:
        ansi:
            enabled: always # 콘솔창 색상 적용

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}

server.port: ${SERVER_PORT}

logging:
  level:
    com.mztrade: info
  file:
    name: log

smtp:
  key: ${SMTP_KEY}

path:
  firebase_admin_key: src/main/resources/serviceAccountKey.json
