name: Testing Server CI/CD

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: mztrade
  IMAGE_NAME: core
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name : Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DEV_DOCKER_ID }}
          password: ${{ secrets.DEV_DOCKER_PW }}
        
      - name: Build the Docker image [arm64]
        run: docker build . --platform linux/arm64 --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64

      - name: Push the Docker image [arm64]
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64
      
      - name: Build the Docker image [amd64]
        run: docker build . --platform linux/amd64 --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64

      - name: Push the Docker image [amd64]
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64
      

      
